version: "3.8"
services:
  frontend:
    image: vue-frontend/avh:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - some-node-modules:/usr/src/app/node_modules

volumes:
  some-node-modules: